### ISSUE TITLE
Show alignment details on click

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#103]
IGV has a few different options for how to show this, either on hover or in a new window on click.

Dalliance uses a bootstrap popover:

![screen shot 2015-04-23 at 8 10 21 pm](https://cloud.githubusercontent.com/assets/98301/7310118/cc39d866-e9f4-11e4-82fb-cd5680187696.png)

cc @arahuja @timodonnell what sort of UI for this do you guys prefer?

**Comment by arahuja** [comment]
The mouseover got very annoying since the boxes were huge and covered the reads.  Also, it wasn't possible to copy and paste information out of them since they went away so quickly.  

I also don't like the look the clickable thing now:
![image](https://cloud.githubusercontent.com/assets/455755/7310205/0e0abb1a-e9f6-11e4-90a6-04192e795041.png)

It was better laid out when it was a mouseover - the table isn't lined up with this.  I think I like the popover since I can show when to open and close them and can even scroll around without them going away. Being able to compare multiple reads would be really nice.

I think being able to configure the information that is displayed the pop-up would be really good as well.

**Comment by ihodes** [comment]
This is actually fixed, but a new issue is filed to improve it: https://github.com/hammerlab/pileup.js/issues/273
