### ISSUE TITLE
Serving data from local file paths

### ISSUE THREAD

**Issue by sim0nj** [hammerlab/pileup.js#219]
Hi,

Nice work with pileup.js - we are interested in integrating it with our portal.

I do not have any experience with Node but from what I can tell pileup.js only supports displaying RemoteFile types from HTTP URLs and not local file system paths - is this correct?

Our portal does not run on Node, so for efficiency and access control it would be ideal if we could display a BAM file through Node by specifying a file path on disk - is this currently possible?

Thanks
Simon

**Comment by danvk** [comment]
Hi Simon, thanks for your interest in pileup.js!

Code running in a web browser can't directly access the file system: it would be a huge security problem. You can work around this by starting up an http server in the directory from which you want to serve data files. The http server needs to support range requests to work with pileup.js, which is why we recommend the node [http-server][1].

[1]: https://github.com/indexzero/http-server

**Comment by sim0nj** [comment]
Thanks for getting back to me Dan,

Right gotcha - I assumed Node was doing some back-end processing to stream the BAM files in a special way and didn't realise it was all browser-based (the require('pileup') threw me).

If it's all just client-side java script in the browser that's great - our server supports range requests.

Cheers
Simon

**Comment by danvk** [comment]
Perfect. I'll close this issue out, then. Feel free to file a new one if/when you run into other issues.
