### ISSUE TITLE
Offsets are out of bounds

### ISSUE THREAD

**Issue by robinandeer** [hammerlab/pileup.js#373]
`Uncaught RangeError: Offsets are out of bounds.`

Hi, trying to understand an error that occur when I try to load a BAM file (I guess). What is this exception telling me? Is there something wrong with the response from the server perhaps?

**Comment by danvk** [comment]
Can you provide more details? Preferably a link that shows the issue, or at
least the BAM file and the range that you're trying to view.

**Comment by robinandeer** [comment]
Sorry I thought perhaps it was a know problem :)

Let's see if this works then... ^^
http://ancient-wildcat-8892.vagrantshare.com/pileup?bam=/vagrant/scout/static/synth3.normal.17.7500000-7515000.bam

The BAM file is the same as in the online demo

**Comment by danvk** [comment]
Thanks for that link. I think the issue may be with your http server. Here's what I see using the pileup demo with the node `http-server`:

<img width="573" alt="screen shot 2015-11-16 at 9 53 57 am" src="https://cloud.githubusercontent.com/assets/98301/11184895/0c7ff5a4-8c48-11e5-842e-dac87d0375f1.png">

It requests bytes 0-3917, which results in a response of length 3918 (because the range is inclusive). Here's what I see yon the vagrantshare page:

<img width="1058" alt="screen shot 2015-11-16 at 9 54 34 am" src="https://cloud.githubusercontent.com/assets/98301/11184910/246095e8-8c48-11e5-82ed-1acb84f8fcac.png">

The response is only 3917 bytes long. Looking at the responses themselves, it seems like the bytes themselves may be different, too.

**Comment by robinandeer** [comment]
Hmm.. 206 requests aren't handled by the server I'm using (Flask) so I found a recipe online but maybe it's doing something wrong then :P

Cool that the vagrant thing worked hehe

**Comment by robinandeer** [comment]
Thanks I'll continue to investigate, perhaps just spin up two servers if all else fails

**Comment by danvk** [comment]
Yeah, 206 requests are essential for any JS genome browser. No sense trying to load a 100+GB BAM file in your poor browser.

A few options:
- For development, node's [http-server][1] is great.
- If you need to stay in Python land, [`RangeHTTPServer`][2] is like `SimpleHTTPServer` but adds support for range requests.
- If you're serving off of HDFS, you could try [igv-httpfs][3]
- With Flask, you're supposed to eventually serve static assets using nginx or Apache. These both support range requests.

Good luck, and let me know if you run into any other issues.

[1]: https://www.npmjs.com/package/http-server
[2]: https://github.com/danvk/RangeHTTPServer/
[3]: http://www.hammerlab.org/2014/12/05/igv-httpfs/

**Comment by robinandeer** [comment]
Thank you! I'll look into your solutions, maybe trying to make Flask work in development is a waste of time, hehe :)

**Comment by robinandeer** [comment]
Oki, I looked into the code being `RangeHTTPServer` and modified it to fit the Flask model and it seems to have done the trick!

Thanks a lot @danvk! :D

**Comment by danvk** [comment]
Great! Thanks for using pileup.
