### ISSUE TITLE
Loading files from the filesystem

### ISSUE THREAD

**Issue by nuin** [hammerlab/pileup.js#447]
Hi 

Is there a way to load files from somewhere else in the filesystem?  For instance I try loading a `bam` and a `bai` files from a location other than the test-data inside the pileup directory and it couldn't find them. When I copied these files over to test-data they loaded OK.

Thanks

**Comment by nuin** [comment]
I was able to overcome this by setting a soft link inside a data directory in the pileup directory. It works, but if there's a more elegant solution I would like to know.

Thanks again

**Comment by armish** [comment]
@nuin: since pileup.js works against an HTTP server, you should always put your files in a directory that gets served by your web-server. The `http-server` that comes with pileup.js is not that ideal for this task, but you can always start new `http-server` instances from the directory that contains your data on a different port and configure the data URLs accordingly. I think your soft-link-workaround is also reasonable especially if you are doing this in an explorative way. Another option is to wrap your pileup.js instance within Electron and with that, you can load local files from any directory just if you are browsing your file system.

I tried to get a similar thing going for a previous hackathon. It is not complete but could guide you get your own thing up and running: https://github.com/armish/pileup.electron

**Comment by nuin** [comment]
Thanks a lot @armish. I will stick with my soft link for now, it's a small load of samples that we analyze weekly and I don't need any heavy weight server for now. I noticed that the `bam` and `bai` are treated as a URL in the assignment, but I thought it would accept things in different areas of the filesystem.

Thanks for pointing out the electron solution.
