### ISSUE TITLE
Nucleotides are not shown at the beginning of the genome track

### ISSUE THREAD

**Issue by etheleon** [hammerlab/pileup.js#449]
In the example http://www.hammerlab.org/pileup/, if you go to positions 0-100, the beginning of the genome track, the nucleotides are not shown. Instead what is seen are black letters, i assume it is undefined.

**Comment by chgibb** [comment]
I'm having the same issue, but running under Electron. Zooming in on that area of the track reveals the string "undefined" replacing the expected A, T, C, G.

**Comment by armish** [comment]
@etheleon @chgibb: that is due to the artifact of the genome assembly and not a pileup issue. The ends, regions with lots of repeats in them, and the regions near the centromere are all hard to sequence and barely mappable. Hence almost all reference genomes of the eukaryotic organisms have `N`s for those regions. Pileup uses dark gray color for those unknown bases hence that is what you are seeing.

Let me know if this is not the issue that you are having and I will re-open this issue for further investigation.

Thanks for checking out pileup, by the way!

**Comment by etheleon** [comment]
Hi @armish, thanks for clarifying this. If I'm interpreting this correctly, the dark grey regions, ie. ends are intentionally assigned undefined? Because my reference sequence does not have any `N`s in it. 

I'm not using this for visualizing eukaryotic genomes. For my case, I'm did a metagenomic assembly and, I want to visualise how the reads pileup against the contigs.

**Comment by armish** [comment]
@etheleon: hmm, what you are seeing sounds like a bug to me. Would you mind providing me with an example setup for me to replicate (and hopefully solve this issue)?

**Comment by chgibb** [comment]
Is there a way to at least prevent the string "undefined" being displayed onto the track?

**Comment by armish** [comment]
hey @chgibb and @etheleon: sorry it took me so long to get to this, but this should be fixed if you use the latest code on the repo. I need to get a few more fixes in and will do another release that will have all these fixes in a few days.

**Comment by chgibb** [comment]
No worries @armish I appreciate it!
