### ISSUE TITLE
Layout options for viewing multiple tracks

### ISSUE THREAD

**Issue by Georgehe4** [hammerlab/pileup.js#463]
Pileup does not support multiple tracks very well due to the flex layout. 
The tracks become squished and are hard to view. 
Are there any plans to address this use case? Having minimum height/pre-fixed track size/user-controllable track height might help resolve some of these issues.

**Comment by armish** [comment]
Hey @Georgehe4 - hmm, that sound weird because unless there is no room at all for the tracks, flex-based sized elements shouldn't collapse. Since all those attributes are being defined in the CSS, you should be able to override them by setting minimums by yourself and not allow that to happen.

How many tracks are we talking about here by the way? And also would be great to have this somewhere like CodePen so I can inspect directly and don't make guesstimates. If that is hard, a screenshot would also help us get started.

Let me know (and sorry for the late reply)

**Comment by armish** [comment]
addressed via #465.
